name: AndroidTest

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: androidsdk/android-30:latest

    steps:
      - name: Checkout reopsitory
        uses: actions/checkout@v2
        
      - name: check
        run: |
          apt-get -y install cpu-checker
          egrep -c '(vmx|svm)' /proc/cpuinfo
          kvm-ok

