name: AndroidTest

on: 
  workflow_dispatch:

jobs:
    instrumentation-tests:
        name: Instrumentation tests
        runs-on: macOS-latest
        timeout-minutes: 60
        strategy:
            fail-fast: true
            matrix:
                api-level: [29, 30]
        steps:
            - uses: actions/checkout@v2
            - name: Instrumentation tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: ${{ matrix.api-level }}
                  arch: x86
                  script: ./gradlew connectedDebugAndroidTest
