name: AndroidTest

on: 
  workflow_dispatch:

jobs:
    test:
        runs-on: macOS-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Run tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 30
            script: ./gradlew connectedDebugAndroidTest
