name: AndroidTest

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: androidsdk/android-30:latest

    steps:
      - name: Checkout reopsitory
        uses: actions/checkout@v2
        
      - name: help
        run: emulator -help
      
      - name: list
        run: emulator -list-avds

