name: AndroidTest

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    
    strategy:
      matrix:
        api-level: [29]
        
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: default
        script: ./gradlew connectedDebugAndroidTest
        
    - name: artifacts report
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: app/build/reports/

  merge:
    runs-on: macos-latest
    needs: "test"
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: check result
      run: ls -R
      
    - name: download artifact
      uses: actions/download-artifact@v2
      with:
        name: reports
      
    - name: check result
      run: ls -R


