name: AndroidTest

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    
    strategy:
      matrix:
        api-level: [23, 24, 25, 26, 27, 28, 29]
        
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: default
        script: ./gradlew connectedDebugAndroidTest

  merge:
    runs-on: macos-latest
    needs: "test"
    
    steps:
      - name: merge report
        run: ls -R app/build | grep report


